name: manage-azure-policy-5da5413c
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Storage_accounts_should_have_shared_access_signature_(SAS)_policies_configured_bc1b984e-ddae-40cc-801a-050a030e4fbe/**'
#      - .github/workflows/manage-azure-policy-5da5413c.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_5da5413c}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Storage_accounts_should_have_shared_access_signature_(SAS)_policies_configured_bc1b984e-ddae-40cc-801a-050a030e4fbe/**
